### ISSUE TITLE
Tidak ada error handling

### ISSUE THREAD

**Issue by priyandari** [zufar-ariq/pengiriman-paket#2]
===Selamat Datang di Jasa Pengiriman Paket ANUGRAH=== 

...........................................................
Masukkan Data Pengiriman Anda

===========================================================
BIODATA
===========================================================
Nama pengirim: a
Nama penerima: 

DETAIL ALAMAT PENERIMA
----------------------
RT/RW: 
Desa/Jalan: 
Kecamatan: 
Kabupaten: 
Provinsi: 
Kode Pos: 

No Telp penerima: 
Berapa jarak pengiriman (dlm km): 
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    jarak= float(input('Berapa jarak pengiriman (dlm km): '))
ValueError: could not convert string to float: ''
 
KeyboardInterrupt


**Comment by priyandari** [comment]
Perhatikan running di atas..
Di isi kosong saja program jalan terus ..

**Comment by zufar-ariq** [comment]
sudah diatasi dengan try except
